<?php

namespace Database\Factories;

use App\Models\Cohort;
use Illuminate\Database\Eloquent\Factories\Factory;

class CourseFactory extends Factory
{
    private static array $courseNames = [
        'Introduction to Programming',
        'Object-Oriented Programming',
        'Data Structures & Algorithms',
        'Database Design & SQL',
        'Web Fundamentals (HTML/CSS)',
        'JavaScript Essentials',
        'Frontend Frameworks',
        'Backend Development',
        'RESTful API Design',
        'Version Control with Git',
        'Linux & Command Line',
        'Networking Fundamentals',
        'Software Engineering Principles',
        'Agile & Scrum',
        'Testing & QA',
        'Security Fundamentals',
        'Cloud Services Overview',
        'Containerization with Docker',
        'CI/CD Pipelines',
        'System Design',
        'Professional Skills & Communication',
        'Graduation Project',
        'Discrete Mathematics for Computer Science',
        'Calculus for Engineers',
        'Linear Algebra & Applications',
        'Probability & Statistics for Computer Science',
        'Computer Organization & Architecture',
        'Operating Systems Concepts',
        'Advanced Data Structures',
        'Design & Analysis of Algorithms',
        'Introduction to Theoretical Computer Science',
        'Automata & Formal Languages',
        'Compiler Design & Construction',
        'Advanced Database Management Systems',
        'NoSQL Databases & Big Data',
        'Distributed Systems',
        'Parallel & Concurrent Programming',
        'Computer Graphics & Visualization',
        'Introduction to Artificial Intelligence',
        'Machine Learning Fundamentals',
        'Deep Learning & Neural Networks',
        'Natural Language Processing',
        'Computer Vision & Image Processing',
        'Data Science & Analytics',
        'Data Warehousing & Data Mining',
        'Human-Computer Interaction',
        'Mobile Application Development (iOS)',
        'Mobile Application Development (Android)',
        'Cross-Platform Mobile Development',
        'Advanced Web Development',
        'Cloud Architecture & Engineering',
        'DevOps Practices & Tools',
        'Cybersecurity Principles',
        'Network Security & Cryptography',
        'Ethical Hacking & Penetration Testing',
        'Digital Forensics',
        'Secure Coding Practices',
        'Information Assurance & Risk Management',
        'Wireless & Mobile Networking',
        'Internet of Things (IoT) Systems',
        'Embedded Systems Programming',
        'Real-Time Operating Systems',
        'Robotics & Autonomous Systems',
        'Game Development Fundamentals',
        'Advanced Game Engine Architecture',
        '3D Modeling & Animation for Games',
        'Virtual & Augmented Reality',
        'Computer Networks & Protocols',
        'User Experience (UX) Design',
        'User Interface (UI) Prototyping',
        'Software Architecture & Design Patterns',
        'Requirements Engineering',
        'Software Metrics & Quality Assurance',
        'Project Management for IT',
        'Enterprise Application Development',
        'Service-Oriented Architecture',
        'Microservices Architecture',
        'Functional Programming Paradigms',
        'Logic Programming & Declarative Languages',
        'Systems Programming in C/C++',
        'Low-Level Programming & Assembly',
        'Digital Logic Design',
        'VHDL & FPGA Design',
        'Quantum Computing Introduction',
        'Bioinformatics & Computational Biology',
        'Geographic Information Systems (GIS)',
        'Blockchain & Distributed Ledger Technology',
        'Full-Stack Web Development',
        'E-Commerce Systems & Platforms',
        'IT Infrastructure & Systems Administration',
        'Network Administration & Configuration',
        'Information Retrieval & Search Engines',
        'Social Media Analytics',
        'Recommender Systems',
        'Reinforcement Learning',
        'Edge & Fog Computing',
        'Cloud Security & Privacy',
        'Malware Analysis & Reverse Engineering',
        'Intrusion Detection & Prevention Systems',
        'Identity & Access Management',
        'Digital Signal Processing',
        'Numerical Methods for Computing',
        'Operations Research & Optimization',
        'Graph Theory & Applications',
        'Combinatorics & Optimization',
        'Information Theory & Coding',
        'Formal Methods in Software Engineering',
        'Software Maintenance & Evolution',
        'Open Source Software Development',
        'Component-Based Software Engineering',
        'Technical Writing for Computer Scientists',
        'Ethics & Technology in Modern Society',
        'Intellectual Property & IT Law',
        'Tech Entrepreneurship & Innovation',
        'Computer Science Internship',
        'Undergraduate Research Methods',
        'Special Topics in Computer Science',
        'Independent Study in Computer Science',
        'Competitive Programming Strategies',
        'Introduction to MATLAB & Simulation',
        'Data Visualization Techniques',
        'Business Intelligence & Analytics',
        'Data Governance & Privacy',
        'High-Performance Computing',
        'GPU Computing with CUDA',
        'Storage Area Networks',
        'Virtualization Technologies',
        'Software-Defined Networking',
        'Network Programmability & Automation',
        'Cyber-Physical Systems',
        'Wearable Computing',
        'Ubiquitous & Pervasive Computing',
        'Game AI Programming',
        'Multiplayer Game Programming',
        'Audio Processing & Synthesis',
        'Computer Music & Acoustics',
        'Semantic Web & Knowledge Graphs',
        'Ontology Engineering',
        'Expert Systems & Knowledge Engineering',
        'Pattern Recognition',
        'Stochastic Processes',
        'Queueing Theory & Performance Evaluation',
        'Computer System Simulation',
        'Hardware Security',
        'Biometric Security Systems',
        'Incident Response & Disaster Recovery',
        'Application Security Testing',
        'Vulnerability Assessment',
        'Cloud-Native Application Development',
        'Serverless Computing Architectures',
        'Web Application Security',
        'Mobile Application Security',
        'Database Security & Auditing',
        'Linux System Administration',
        'Windows Server Administration',
        'Directory Services & Active Directory',
        'Enterprise Network Routing',
        'Enterprise Network Switching',
        'Advanced Linux Kernel Programming',
        'Device Driver Development',
        'Compiler Optimization Techniques',
        'Programming Language Semantics',
        'Type Theory & Lambda Calculus',
        'Computational Complexity',
        'Cryptography & Network Security II',
        'Applied Cryptography',
        'Public Key Infrastructure',
        'Secure Protocols & Standards',
        'Cyber Warfare & National Security',
        'Privacy-Enhancing Technologies',
        'Algorithmic Game Theory',
        'Computational Geometry',
        'Approximation Algorithms',
        'Randomized Algorithms',
        'Online & Streaming Algorithms',
        'Parallel Algorithms',
        'Distributed Algorithms',
        'Heuristic Search & Optimization',
        'Evolutionary Computation',
        'Swarm Intelligence',
        'Fuzzy Logic & Systems',
        'Speech Recognition & Synthesis',
        'Text Mining & Analytics',
        'Big Data Frameworks (Hadoop/Spark)',
        'Data Pipeline Engineering',
        'Stream Processing Architecture',
        'Graph Databases & Analytics',
        'NoSQL Data Modeling',
        'Relational Query Optimization',
        'Database Administration',
        'Enterprise Resource Planning (ERP) Systems',
        'Customer Relationship Management (CRM) Systems',
        'Supply Chain Management Systems',
        'Financial Computing & FinTech',
        'Algorithmic Trading Systems',
        'Health Informatics',
        'Clinical Decision Support Systems',
        'Senior Capstone Project I',
        'Senior Capstone Project II',
    ];

    public function definition(): array
    {
        return [
            'cohort_id' => Cohort::factory(),
            'name' => $this->faker->randomElement(self::$courseNames),
        ];
    }
}
